# Generated by Django 3.1.4 on 2021-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='category',
            field=models.CharField(choices=[('CROP', 'CROP'), ('MACHINERY', 'MACHINERY'), ('PRODUCT', 'PRODUCT')], default='LAB', max_length=10),
        ),
    ]
