# Generated by Django 3.1.4 on 2021-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transport_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='category',
            field=models.CharField(choices=[('CROP', 'CROP'), ('MACHINERY', 'MACHINERY'), ('PRODUCT', 'PRODUCT')], default='CROP', max_length=10),
        ),
    ]
