# Generated by Django 3.1.4 on 2021-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211201_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='test_name',
            field=models.CharField(max_length=500),
        ),
    ]
