# Generated by Django 3.1.4 on 2021-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211201_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuarance',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuarance',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuarance',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuarance',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuarance',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='contact_info',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='test_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='testing_at',
            field=models.CharField(blank=True, choices=[('PLACE', 'PLACE'), ('LAB', 'LAB')], default='LAB', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='category',
            field=models.CharField(blank=True, choices=[('CROP', 'CROP'), ('MACHINERY', 'MACHINERY'), ('PRODUCT', 'PRODUCT')], default='CROP', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.ico', null=True, upload_to='transport/profile_image/'),
        ),
    ]
