# Generated by Django 3.1.4 on 2021-12-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seller_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
