# Generated by Django 3.1.4 on 2021-12-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seller_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='pincode',
        ),
    ]
