# Generated by Django 3.1.4 on 2021-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seller_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='contact_info',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
