# Generated by Django 3.1.4 on 2021-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211227_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
