# Generated by Django 3.1.4 on 2021-12-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211227_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='testing_at',
            field=models.CharField(blank=True, choices=[('PLACE', 'PLACE'), ('LAB', 'LAB')], default='LAB', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='category',
            field=models.CharField(blank=True, choices=[('CROP', 'CROP'), ('MACHINERY', 'MACHINERY'), ('PRODUCT', 'PRODUCT')], default='CROP', max_length=20, null=True),
        ),
    ]
